# Generated by Django 6.0.4 on 2026-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='content',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_a',
            new_name='option_a_ru',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_b',
            new_name='option_b_ru',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_c',
            new_name='option_c_ru',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question_ru',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_kz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_kz',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='description_kz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='title_kz',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a_kz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b_kz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c_kz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='question_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_kz',
            field=models.TextField(blank=True),
        ),
    ]
