# Generated by Django 6.0.4 on 2026-04-29 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_content_lesson_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200)),
                ('title_kz', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('description_ru', models.TextField(blank=True)),
                ('description_kz', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['section__order', 'order']},
        ),
        migrations.AddField(
            model_name='module',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.section'),
        ),
    ]
