# Generated by Django 6.0.4 on 2026-05-24 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def ensure_existing_scoring_schema(apps, schema_editor):
    connection = schema_editor.connection
    Question = apps.get_model('courses', 'Question')
    QuizResult = apps.get_model('courses', 'QuizResult')

    table_names = connection.introspection.table_names()

    with connection.cursor() as cursor:
        question_columns = {
            column.name
            for column in connection.introspection.get_table_description(
                cursor,
                Question._meta.db_table,
            )
        }

    for field_name in ('base_points', 'penalty_points'):
        if field_name not in question_columns:
            schema_editor.add_field(Question, Question._meta.get_field(field_name))

    if QuizResult._meta.db_table not in table_names:
        schema_editor.create_model(QuizResult)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_section_alter_module_options_module_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='question',
                    name='base_points',
                    field=models.PositiveIntegerField(default=10),
                ),
                migrations.AddField(
                    model_name='question',
                    name='penalty_points',
                    field=models.PositiveIntegerField(default=5),
                ),
                migrations.CreateModel(
                    name='QuizResult',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('score', models.IntegerField(default=0)),
                        ('max_score', models.PositiveIntegerField(default=0)),
                        ('correct_count', models.PositiveIntegerField(default=0)),
                        ('total_questions', models.PositiveIntegerField(default=0)),
                        ('details', models.JSONField(blank=True, default=list)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_results', to='courses.lesson')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
            ],
        ),
        migrations.RunPython(
            ensure_existing_scoring_schema,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
