# Generated by Django 6.0.4 on 2026-05-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_image_url_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='penalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
