# Generated by Django 6.0.4 on 2026-05-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_question_penalty_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='penalty_points',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
