# Generated by Django 6.0.4 on 2026-05-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_question_penalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_kz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_ru',
            field=models.TextField(blank=True),
        ),
    ]
